word= [
    "abandon", "ability", "able", "about", "above", "abroad", "absent", "abuse", "accept", "access",
    "accomplish", "account", "achieve", "acquire", "address", "advance", "affect", "afford", "agency", "agree",
    "amazing", "analyze", "ancient", "animal", "apply", "appoint", "approve", "arrange", "assess", "assist",
    "attend", "author", "average", "balance", "become", "benefit", "beyond", "breathe", "bright", "brother",
    "burden", "capture", "change", "choice", "circle", "conclude", "connect", "control", "create", "decide",
    "define", "deliver", "design", "develop", "discuss", "disease", "distant", "divide", "doubt", "educate",
    "effort", "enable", "encourage", "engage", "enrich", "entire", "escape", "expect", "factor", "failure",
    "famous", "friend", "future", "gather", "growth", "handle", "impact", "improve", "include", "income",
    "indicate", "inspire", "issue", "journey", "justice", "knowing", "listen", "maintain", "manage", "mature",
    "medical", "mention", "modern", "natural", "nature", "observe", "option", "origin", "people", "prepare",
    "prevent", "process", "produce", "project", "public", "purpose", "rebuild", "record", "reflect", "regard",
    "remain", "repair", "report", "resolve", "retain", "return", "select", "service", "society", "source",
    "support", "system", "teacher", "tend", "theory", "threat", "travel", "unique", "update", "usability",
    "urgent", "values", "venture", "victory", "vision", "weaken", "welfare", "witness", "wonder", "worry",
    "ability", "absent", "action", "activity", "advice", "agency", "amount", "animal", "answer", "appeal",
    "approach", "arise", "arrange", "attempt", "authority", "balance", "benefit", "beyond", "capture", "cause",
    "change", "choice", "conclude", "connect", "control", "create", "culture", "damage", "debate", "decide",
    "deliver", "design", "develop", "discuss", "disease", "distance", "doubt", "educate", "effort", "enable",
    "engage", "escape", "expect", "factor", "failure", "family", "famous", "focus", "friend", "future",
    "gather", "growth", "handle", "impact", "include", "income", "indicate", "inspire", "issue", "journey",
    "justice", "knowing", "listen", "maintain", "manage", "modern", "natural", "nature", "observe", "option",
    "origin", "people", "prepare", "prevent", "process", "produce", "project", "public", "purpose", "rebuild",
    "record", "reflect", "regard", "remain", "repair", "report", "resolve", "retain", "return", "select",
    "service", "society", "source", "support", "system", "teacher", "tend", "theory", "threat", "travel",
    "unique", "update", "urgent", "values", "venture", "victory", "vision", "weaken", "welfare", "witness",
    "wonder", "worry", "abstract", "account", "advance", "align", "analyze", "answer", "approach", "arrange",
    "balance", "benefit", "beyond", "capture", "cause", "change", "choice", "conclude", "connect", "control",
    "create", "culture", "damage", "debate", "decide", "deliver", "design", "develop", "discuss", "distance",
    "doubt", "educate", "effort", "enable", "engage", "escape", "expect", "factor", "failure", "family",
    "famous", "focus", "friend", "future", "gather", "growth", "handle", "impact", "include", "income",
    "indicate", "inspire", "issue", "journey", "justice", "knowing", "listen", "maintain", "manage", "modern",
    "natural", "nature", "observe", "option", "origin", "people", "prepare", "prevent", "process", "produce",
    "project", "public", "purpose", "rebuild", "record", "reflect", "regard", "remain", "repair", "report",
    "resolve", "retain", "return", "select", "service", "society", "source", "support", "system", "teacher",
    "tend", "theory", "threat", "travel", "unique", "update", "urgent", "values", "venture", "victory",
    "vision", "weaken", "welfare", "witness", "wonder", "worry"
]
